apiVersion: v1
kind: Service
metadata:
  name: {{ include "miudinho-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miudinho-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "miudinho-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.ports.webhook }}
      targetPort: webhook
    - name: probe
      port: {{ .Values.service.ports.probe }}
      targetPort: probe
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
