package alertmanager

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/wellbastos/miudinho-agent/internal/incidents"
	appmetrics "github.com/wellbastos/miudinho-agent/internal/metrics"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type Handler struct {
	client client.Client
}

type webhookPayload struct {
	Alerts []webhookAlert `json:"alerts"`
}

type webhookAlert struct {
	Status       string            `json:"status"`
	Labels       map[string]string `json:"labels"`
	Annotations  map[string]string `json:"annotations"`
	StartsAt     string            `json:"startsAt"`
	EndsAt       string            `json:"endsAt"`
	GeneratorURL string            `json:"generatorURL"`
	Fingerprint  string            `json:"fingerprint"`
}

type fakeAlertRequest struct {
	Namespace        string `json:"namespace"`
	Service          string `json:"service"`
	Job              string `json:"job"`
	Severity         string `json:"severity"`
	Summary          string `json:"summary"`
	Description      string `json:"description"`
	Status           string `json:"status"`
	GitHubRepository string `json:"github_repository"`
}

func NewHandler(c client.Client) *Handler {
	return &Handler{client: c}
}

func (h *Handler) HandleAlerts(w http.ResponseWriter, r *http.Request) {
	log := ctrl.Log.WithName("alertmanager-webhook")
	startedAt := time.Now()
	result := "accepted"
	defer func() {
		appmetrics.RecordAlertWebhookRequest(result, time.Since(startedAt))
	}()

	if r.Method != http.MethodPost {
		result = "method_not_allowed"
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var payload webhookPayload
	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		result = "bad_request"
		log.Error(err, "failed to decode webhook payload", "remoteAddr", r.RemoteAddr)
		http.Error(w, "invalid payload", http.StatusBadRequest)
		return
	}

	log.Info("webhook received alerts", "count", len(payload.Alerts), "remoteAddr", r.RemoteAddr)

	var failed []string
	for _, alert := range payload.Alerts {
		if err := h.upsertIncident(r.Context(), alert); err != nil {
			log.Error(err, "failed to upsert incident from webhook", "alertname", alert.Labels["alertname"], "namespace", alert.Labels["namespace"])
			failed = append(failed, err.Error())
		} else {
			log.Info("incident upserted from webhook", "alertname", alert.Labels["alertname"], "namespace", alert.Labels["namespace"], "status", alert.Status)
		}
	}

	if len(failed) > 0 {
		result = "partial_error"
		http.Error(w, fmt.Sprintf("failed to persist %d alerts", len(failed)), http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusAccepted)
}

func (h *Handler) HandleFakeAlert(w http.ResponseWriter, r *http.Request) {
	log := ctrl.Log.WithName("alertmanager-webhook")
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	req := fakeAlertRequest{
		Namespace:   "default",
		Service:     "miudinho-test",
		Severity:    "warning",
		Summary:     "Miudinho test alert",
		Description: "Synthetic alert generated by test endpoint",
		Status:      "firing",
	}
	if r.Body != nil {
		defer func() {
			_ = r.Body.Close()
		}()
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
			http.Error(w, "invalid payload", http.StatusBadRequest)
			return
		}
	}

	if req.Namespace == "" {
		req.Namespace = "default"
	}
	if req.Service == "" {
		req.Service = "miudinho-test"
	}
	if req.Job == "" {
		req.Job = req.Service
	}
	if req.Severity == "" {
		req.Severity = "warning"
	}
	if req.Summary == "" {
		req.Summary = "Miudinho test alert"
	}
	if req.Description == "" {
		req.Description = "Synthetic alert generated by test endpoint"
	}
	if req.Status == "" {
		req.Status = "firing"
	}

	alert := webhookAlert{
		Status: req.Status,
		Labels: map[string]string{
			"alertname":           "MiudinhoSyntheticTestAlert",
			"namespace":           req.Namespace,
			"service":             req.Service,
			"job":                 req.Job,
			"severity":            req.Severity,
			"managed_by":          "miudinho-agent-test-endpoint",
			"miudinho_test_alert": "true",
		},
		Annotations: map[string]string{
			"summary":     req.Summary,
			"description": req.Description,
		},
		StartsAt: time.Now().UTC().Format(time.RFC3339),
	}
	if req.GitHubRepository != "" {
		alert.Labels["github_repository"] = req.GitHubRepository
	}

	log.Info("fake alert request received", "namespace", req.Namespace, "service", req.Service, "status", req.Status)
	if err := h.upsertIncident(r.Context(), alert); err != nil {
		log.Error(err, "failed to upsert fake alert", "namespace", req.Namespace, "service", req.Service)
		http.Error(w, fmt.Sprintf("failed to create fake alert: %v", err), http.StatusInternalServerError)
		return
	}

	fp := incidents.CanonicalFingerprint(incidents.ObservedAlert{
		Source:      "alertmanager",
		Status:      alert.Status,
		Labels:      alert.Labels,
		Annotations: alert.Annotations,
		StartsAt:    alert.StartsAt,
	})

	w.Header().Set("Content-Type", "application/json")
	_ = writeJSON(w, http.StatusAccepted, map[string]any{
		"ok":            true,
		"message":       "synthetic alert accepted; GitHub issue will be created asynchronously by the reconciler",
		"incident_name": incidents.IncidentNameForFingerprint(fp),
		"namespace":     req.Namespace,
		"service":       req.Service,
		"fingerprint":   fp,
		"status":        req.Status,
	})
}

func (h *Handler) upsertIncident(ctx context.Context, alert webhookAlert) error {
	_, _, err := incidents.UpsertObservedAlert(ctx, h.client, incidents.ObservedAlert{
		Source:       "alertmanager",
		Status:       alert.Status,
		Labels:       alert.Labels,
		Annotations:  alert.Annotations,
		StartsAt:     alert.StartsAt,
		EndsAt:       alert.EndsAt,
		GeneratorURL: alert.GeneratorURL,
		Fingerprint:  alert.Fingerprint,
	}, "webhook")
	return err
}
