//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func copyStringMap(in map[string]string) map[string]string {
	if in == nil {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
func copyAnyMap(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (in *IncidentIdentity) DeepCopyInto(out *IncidentIdentity) { *out = *in }
func (in *IncidentIdentity) DeepCopy() *IncidentIdentity {
	if in == nil {
		return nil
	}
	out := new(IncidentIdentity)
	*out = *in
	return out
}

func (in *PredictiveIncidentSpec) DeepCopyInto(out *PredictiveIncidentSpec) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
	out.Alert = copyAnyMap(in.Alert)
	out.Signals = copyAnyMap(in.Signals)
}
func (in *PredictiveIncidentSpec) DeepCopy() *PredictiveIncidentSpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveIncidentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EvidenceItem) DeepCopyInto(out *EvidenceItem) { *out = *in; out.Data = copyAnyMap(in.Data) }
func (in *EvidenceItem) DeepCopy() *EvidenceItem {
	if in == nil {
		return nil
	}
	out := new(EvidenceItem)
	in.DeepCopyInto(out)
	return out
}

func (in *RCAStatus) DeepCopyInto(out *RCAStatus) { *out = *in; out.Details = copyAnyMap(in.Details) }
func (in *RCAStatus) DeepCopy() *RCAStatus {
	if in == nil {
		return nil
	}
	out := new(RCAStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GitHubIssueStatus) DeepCopyInto(out *GitHubIssueStatus) {
	*out = *in
	if in.EscalatedTeams != nil {
		out.EscalatedTeams = append([]string(nil), in.EscalatedTeams...)
	}
}
func (in *GitHubIssueStatus) DeepCopy() *GitHubIssueStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubIssueStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertmanagerStatus) DeepCopyInto(out *AlertmanagerStatus) { *out = *in }
func (in *AlertmanagerStatus) DeepCopy() *AlertmanagerStatus {
	if in == nil {
		return nil
	}
	out := new(AlertmanagerStatus)
	*out = *in
	return out
}

func (in *ActionStatus) DeepCopyInto(out *ActionStatus) {
	*out = *in
	out.Args = copyAnyMap(in.Args)
	out.Result = copyAnyMap(in.Result)
}
func (in *ActionStatus) DeepCopy() *ActionStatus {
	if in == nil {
		return nil
	}
	out := new(ActionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PredictiveIncidentStatus) DeepCopyInto(out *PredictiveIncidentStatus) {
	*out = *in
	if in.Evidence != nil {
		out.Evidence = make([]EvidenceItem, len(in.Evidence))
		for i := range in.Evidence {
			in.Evidence[i].DeepCopyInto(&out.Evidence[i])
		}
	}
	in.RCA.DeepCopyInto(&out.RCA)
	if in.Actions != nil {
		out.Actions = make([]ActionStatus, len(in.Actions))
		for i := range in.Actions {
			in.Actions[i].DeepCopyInto(&out.Actions[i])
		}
	}
	in.GitHub.DeepCopyInto(&out.GitHub)
	in.Alerting.DeepCopyInto(&out.Alerting)
}
func (in *PredictiveIncidentStatus) DeepCopy() *PredictiveIncidentStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveIncidentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PredictiveIncident) DeepCopyInto(out *PredictiveIncident) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *PredictiveIncident) DeepCopy() *PredictiveIncident {
	if in == nil {
		return nil
	}
	out := new(PredictiveIncident)
	in.DeepCopyInto(out)
	return out
}
func (in *PredictiveIncident) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PredictiveIncidentList) DeepCopyInto(out *PredictiveIncidentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PredictiveIncident, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *PredictiveIncidentList) DeepCopy() *PredictiveIncidentList {
	if in == nil {
		return nil
	}
	out := new(PredictiveIncidentList)
	in.DeepCopyInto(out)
	return out
}
func (in *PredictiveIncidentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PolicySelector) DeepCopyInto(out *PolicySelector) {
	*out = *in
	out.MatchLabels = copyStringMap(in.MatchLabels)
	if in.Severities != nil {
		out.Severities = append([]string(nil), in.Severities...)
	}
}
func (in *PolicySelector) DeepCopy() *PolicySelector {
	if in == nil {
		return nil
	}
	out := new(PolicySelector)
	in.DeepCopyInto(out)
	return out
}
func (in *GuardrailsSpec) DeepCopyInto(out *GuardrailsSpec) {
	*out = *in
	if in.BlockIfReasons != nil {
		out.BlockIfReasons = append([]string(nil), in.BlockIfReasons...)
	}
	if in.AllowedActions != nil {
		out.AllowedActions = append([]string(nil), in.AllowedActions...)
	}
}
func (in *GuardrailsSpec) DeepCopy() *GuardrailsSpec {
	if in == nil {
		return nil
	}
	out := new(GuardrailsSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *RuleWhen) DeepCopyInto(out *RuleWhen) { *out = *in }
func (in *RuleWhen) DeepCopy() *RuleWhen {
	if in == nil {
		return nil
	}
	out := new(RuleWhen)
	*out = *in
	return out
}
func (in *PolicyAction) DeepCopyInto(out *PolicyAction) { *out = *in; out.Args = copyAnyMap(in.Args) }
func (in *PolicyAction) DeepCopy() *PolicyAction {
	if in == nil {
		return nil
	}
	out := new(PolicyAction)
	in.DeepCopyInto(out)
	return out
}
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
	if in.Actions != nil {
		out.Actions = make([]PolicyAction, len(in.Actions))
		for i := range in.Actions {
			in.Actions[i].DeepCopyInto(&out.Actions[i])
		}
	}
}
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoRemediationPolicySpec) DeepCopyInto(out *AutoRemediationPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Guardrails.DeepCopyInto(&out.Guardrails)
	if in.Rules != nil {
		out.Rules = make([]PolicyRule, len(in.Rules))
		for i := range in.Rules {
			in.Rules[i].DeepCopyInto(&out.Rules[i])
		}
	}
}
func (in *AutoRemediationPolicySpec) DeepCopy() *AutoRemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoRemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}
func (in *AutoRemediationPolicyStatus) DeepCopyInto(out *AutoRemediationPolicyStatus) { *out = *in }
func (in *AutoRemediationPolicyStatus) DeepCopy() *AutoRemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoRemediationPolicyStatus)
	*out = *in
	return out
}
func (in *AutoRemediationPolicy) DeepCopyInto(out *AutoRemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *AutoRemediationPolicy) DeepCopy() *AutoRemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoRemediationPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *AutoRemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *AutoRemediationPolicyList) DeepCopyInto(out *AutoRemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AutoRemediationPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *AutoRemediationPolicyList) DeepCopy() *AutoRemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(AutoRemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *AutoRemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SLOServiceRef) DeepCopyInto(out *SLOServiceRef) { *out = *in }
func (in *SLOServiceRef) DeepCopy() *SLOServiceRef {
	if in == nil {
		return nil
	}
	out := new(SLOServiceRef)
	*out = *in
	return out
}
func (in *SLOObjective) DeepCopyInto(out *SLOObjective) { *out = *in }
func (in *SLOObjective) DeepCopy() *SLOObjective {
	if in == nil {
		return nil
	}
	out := new(SLOObjective)
	*out = *in
	return out
}
func (in *SLOSignals) DeepCopyInto(out *SLOSignals) { *out = *in }
func (in *SLOSignals) DeepCopy() *SLOSignals {
	if in == nil {
		return nil
	}
	out := new(SLOSignals)
	*out = *in
	return out
}
func (in *SLOPolicySpec) DeepCopyInto(out *SLOPolicySpec) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.Objective.DeepCopyInto(&out.Objective)
	in.Signals.DeepCopyInto(&out.Signals)
}
func (in *SLOPolicySpec) DeepCopy() *SLOPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SLOPolicySpec)
	in.DeepCopyInto(out)
	return out
}
func (in *SLOPolicyStatus) DeepCopyInto(out *SLOPolicyStatus) { *out = *in }
func (in *SLOPolicyStatus) DeepCopy() *SLOPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SLOPolicyStatus)
	*out = *in
	return out
}
func (in *SLOPolicy) DeepCopyInto(out *SLOPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *SLOPolicy) DeepCopy() *SLOPolicy {
	if in == nil {
		return nil
	}
	out := new(SLOPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *SLOPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *SLOPolicyList) DeepCopyInto(out *SLOPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SLOPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *SLOPolicyList) DeepCopy() *SLOPolicyList {
	if in == nil {
		return nil
	}
	out := new(SLOPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *SLOPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

var _ runtime.Object = &PredictiveIncident{}
var _ runtime.Object = &PredictiveIncidentList{}
var _ runtime.Object = &AutoRemediationPolicy{}
var _ runtime.Object = &AutoRemediationPolicyList{}
var _ runtime.Object = &SLOPolicy{}
var _ runtime.Object = &SLOPolicyList{}
var _ = metav1.Now
