apiVersion: sre.o11y.io/v1alpha1
kind: AutoRemediationPolicy
metadata:
  name: default-observe
  namespace: o11y
spec:
  selector:
    namespace: o11y
    severities: ["critical","high","warning"]
  guardrails:
    minAvailableReplicas: 2
    restartCooldownSeconds: 900
    blockIfReasons: ["OOMKilled","ImagePullBackOff","ErrImagePull","CreateContainerConfigError"]
    allowedActions: ["observeOnly","escalate"]
  rules:
    - when:
        source: "alertmanager"
      actions:
        - type: "observeOnly"
    - when:
        source: "predictive"
      actions:
        - type: "observeOnly"
