apiVersion: miudinho.o11y.io/v1alpha1
kind: SLOPolicy
metadata:
  name: global-slo
spec:
  excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
    - o11y
  service:
    matchLabels:
      miudinho.o11y.io/enabled: "true"
  objective:
    target: 0.999
    window: "30d"
  signals:
    http5xx:
      errorRateThresholdPct: 1.0
      slopeThreshold: 0.0
      min5xxRPS: 0.1
    oom:
      timeToOomThresholdSeconds: 900
    latency:
      enabled: true
  scheduleSeconds: 120
