replicaCount: 1

image:
  repository: ghcr.io/wellbastos/miudinho-agent
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: "miudinho-agent" 
fullnameOverride: "miudinho-agent"

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

leaderElection:
  enabled: false

service:
  type: ClusterIP
  annotations: {}
  ports:
    webhook: 8090
    probe: 8080
    metrics: 8081

serviceMonitor:
  enabled: false
  namespace: ""
  labels: {}
  annotations: {}
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics
  honorLabels: false

podMonitor:
  enabled: false
  namespace: ""
  labels: {}
  annotations: {}
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics
  honorLabels: false

secret:
  create: true
  name: ""
  googleApiKey: "COLOQUE_AQUI"
  githubToken: "COLOQUE_AQUI"
  googleChatIncidentsWebhookUrl: "COLOQUE_AQUI"

env:
  alertWebhookAddr: ":8090"
  alertPollInterval: "30s"
  alertSourcesEnabled: "prometheus,alertmanager"
  alertmanagerOutboundUrl: "http://alertmanager-operated.o11y.svc.cluster.local:9093/api/v2/alerts"
  alertmanagerApiUrl: "http://alertmanager-operated.o11y.svc.cluster.local:9093/api/v2/alerts"
  promUrl: "http://thanos-query.o11y.svc.cluster.local:10901"
  tempoUrl: "http://tempo.o11y.svc.cluster.local:3100"
  tempoPredictivePath: "api/search"
  tempoPredictiveQueryParam: "q"
  ollamaBaseUrl: "http://ollama.o11y.svc.cluster.local:11434"
  ollamaModel: "llama3.1:8b"
  geminiBaseUrl: "https://generativelanguage.googleapis.com"
  geminiModel: "gemini-1.5-pro"
  systemPrompt: "Você é um Agente SRE de produção. Responda sempre em JSON válido com classification, confidence, summary, evidence, prom_queries, actions, rollback_or_next_steps, escalation. Para predictive, priorize low-risk. Confidence < 0.70 => sem mudanças."
  approverPrompt: "Você é o Change Approver. Responda somente JSON com approved, risk_level, reasons, required_changes. Bloqueie ações arriscadas e qualquer confidence < 0.70."
  githubOwner: "wellbastos"
  githubRepositoryPrefix: "apps-"
  githubProductName: "miudinho-agent" # repo name
  githubN2Teams: "sre-editor,sre-viewer,sre-admin"
  llmRoutingMode: "ollama_only"
  autoObserveOnly: "true"
  observeOnlyTtlSeconds: "300"
  executeActions: "false"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
